apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: springbootapp
  template:
    metadata:
      labels:
        io.kompose.service: springbootapp
    spec:
      containers:
        - image: oad3jp999/application-springboot:0.0.1
          name: springbootapp
          ports:
            - containerPort: 8080
      restartPolicy: Always
