apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp-deployment
  labels:
    tags.datadoghq.com/env: app
    tags.datadoghq.com/service: springbootapp-deployment
    tags.datadoghq.com/version: 0.0.10
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: springbootapp
  template:
    metadata:
      name: springbootapp
      labels:
        io.kompose.service: springbootapp
        tags.datadoghq.com/env: app
        tags.datadoghq.com/service: springbootapp-deployment
        tags.datadoghq.com/version: 0.0.10
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.38.1
      annotations:
        ad.datadoghq.com/springbootapp.checks: |
          {
            "jmx": {
              "init_config": {
                "is_jmx": true,
                "collect_default_metrics": true
              },
              "instances": [{
                "host": "%%host%%",
                "port": "8081"
              }]
            }
          }
    spec:
      containers:
        - image: oad3jp999/application-springboot:0.0.1
          name: springbootapp
          ports:
            - containerPort: 8080
            - containerPort: 8126
          env:
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      restartPolicy: Always
