apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: sprongbootapp
  name: sprongbootapp
spec:
  type: NodePort
  ports:
    - name: "49161"
      port: 49161
      targetPort: 8080
      nodePort: 30001
  selector:
    io.kompose.service: sprongbootapp
