trigger:
  - none

pool:
  name: Self-Hosted-Linux

variables:
  - group: variablegroup

stages:
  - stage: UndeployStage
    jobs:
      - job: Undeploy
        displayName: "Undeploy"
        continueOnError: false
        workspace:
          clean: outputs
        steps:
          - checkout: self
            clean: true

          - bash: |
              source ./env-files/my_env01_vars.env
              source ./gradle.properties

              echo ----- git clone config repo
              chmod 744 ./shell/git-clone.sh
              ./shell/git-clone.sh --url ${GIT_URL} \
              --github_user $(github-user) \
              --github_token $(github-token)

              echo ----- ls -la
              ls -la

              kubectl delete -f $GIT_CONFIG_REPO/$DEPLOY_YML
              # kubectl delete -f $GIT_CONFIG_REPO/$CONFIGMAP_YML

            displayName: "release"
